"""
LinkedIn Authentic Sector Commenting Engine (Anti-AI Persona).
Drafts high-caliber, human-sounding CTO comments on FinTech, PropTech, and AI posts
across Saudi Arabia & GCC to organically elevate profile visibility.
Authored strictly as Mohamed Elbaloty, CTO @ Sahalat.
"""

from datetime import datetime
import json
import logging
import os
import re
from pathlib import Path
from typing import Dict, List, Optional
import urllib.parse
import requests

from google import genai
from google.genai import types

from config import BASE_DIR, GEMINI_API_KEY, TEXT_MODEL
from fetcher import fetch_unread_articles
from linkedin_api import extract_urn_from_linkedin_url, publish_comment_to_linkedin

logger = logging.getLogger(__name__)

COMMENT_CONFIG_FILE = BASE_DIR / "comment_settings.json"


def load_comment_settings() -> Dict[str, any]:
    """Loads commenting configuration from disk or defaults."""
    if COMMENT_CONFIG_FILE.exists():
        try:
            with open(COMMENT_CONFIG_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.warning("Error reading %s: %s", COMMENT_CONFIG_FILE, e)

    default_settings = {
        "auto_comment_enabled": False,  # Disabled until user confirms test
        "max_daily_comments": 4,
        "comments_today": 0,
        "last_comment_date": datetime.now().strftime("%Y-%m-%d"),
        "last_comment_time": None,
        "target_sectors": ["FinTech", "PropTech", "AI Infrastructure", "SAMA Regulations"],
        "history": []
    }
    save_comment_settings(default_settings)
    return default_settings


def save_comment_settings(settings: Dict[str, any]) -> None:
    """Persists commenting settings to disk."""
    try:
        with open(COMMENT_CONFIG_FILE, "w", encoding="utf-8") as f:
            json.dump(settings, f, indent=2, ensure_ascii=False)
    except Exception as e:
        logger.error("Failed to save comment settings: %s", e)


def clean_anti_ai_comment(text: str) -> str:
    """
    Cleanses and ensures the comment strictly avoids AI cliches and pleasantries.
    """
    cleaned = text.strip()
    # Remove enclosing quotes if any
    if (cleaned.startswith('"') and cleaned.endswith('"')) or (cleaned.startswith("'") and cleaned.endswith("'")):
        cleaned = cleaned[1:-1].strip()

    # Disallowed greetings and compliments
    banned_prefixes = [
        r"^(مقال|بوست|طرح|منشور)\s+(رائع|ممتاز|قيم|جميل|مهم)[،,.\s]*",
        r"^(أحسنت|شكراً لك|شكرا جزيلا|سلمت يداك|بارك الله فيك)[،,.\s]*",
        r"^(great post|fascinating post|insightful share|thanks for sharing|100% agree)[,!.\s]*",
        r"^(اتفق معك تماما|أتفق معك تماماً)[،,.\s]*",
        r"^(تلخيصاً|باختصار|في رأيي|في الحقيقة)[،,.\s]*",
    ]
    for pattern in banned_prefixes:
        cleaned = re.sub(pattern, "", cleaned, flags=re.IGNORECASE).strip()

    # Capitalize first character if English
    if cleaned and cleaned[0].isascii():
        cleaned = cleaned[0].upper() + cleaned[1:]

    return cleaned


class CommentGenerator:
    """Generates authentic, pragmatic CTO comments using Gemini."""

    def __init__(self, api_key: Optional[str] = None):
        key = (api_key or GEMINI_API_KEY).strip()
        if not key:
            raise ValueError("GEMINI_API_KEY is missing for comment generator.")
        self.client = genai.Client(api_key=key)
        self.text_model = TEXT_MODEL

    def generate_comment(
        self,
        post_content: str,
        post_title: str = "",
        post_author: str = "",
        sector: str = "FinTech / PropTech / AI",
    ) -> str:
        """
        Drafts a high-impact, authentic comment that reads 100% like an experienced CTO.
        """
        system_instruction = (
            "You are Mohamed Elbaloty, CTO @ Sahalat. You are a senior engineering leader, software architect, "
            "and active technical executive in FinTech (التقنية المالية) and PropTech (التقنية العقارية) in Saudi Arabia and the GCC.\n\n"
            "YOUR OBJECTIVE:\n"
            "Write a sharp, authentic, and high-value comment on a LinkedIn post in your industry. "
            "The comment must stand out to founders, investors, and other CTOs as pure engineering/product insight. "
            "It must NEVER look or feel like it was generated by AI.\n\n"
            "STRICT RULES (VIOLATING THESE WILL RUIN THE PROFILE REPUTATION):\n"
            "1. NO GREETINGS OR COMPLIMENTS: Never write 'مقال رائع', 'أحسنت', 'شكراً على المشاركة', 'Great post', 'Fascinating read', 'Totally agree'. Jump directly into the technical or economic core.\n"
            "2. NO SUMMARIES: Do not recap what the author just said. They already know what they wrote.\n"
            "3. NO AI CLICHES: Never use words like 'تعتبر حجر الزاوية', 'ثورة حقيقية', 'في عالمنا المتسارع', 'game-changer', 'delve', 'testament', 'revolutionize', 'unleash'.\n"
            "4. CONCISENESS: Strictly 2 to 4 sentences (between 35 and 75 words). A senior CTO is busy; their comments are dense, focused, and punchy.\n"
            "5. REAL-WORLD DEPTH: Mention real operational realities—such as SAMA sandbox compliance, Open Banking API latencies, webhook reliability, instant settlement reconciliation, automated property valuation (AVM) accuracy, or unit economics in the Saudi market.\n"
            "6. LANGUAGE: Natural Arabic mixed seamlessly with standard English tech terms (e.g., APIs, latency, SLA, unit economics, escrow, sandbox, microservices), OR natural English if the target post is entirely in English.\n"
            "7. Output ONLY the raw comment text. Do NOT add quotation marks, explanations, or meta-talk like 'إليك تعليق بصفة رئيس تقني:' or 'تعليق:'. Start directly with the actual statement."
        )

        user_prompt = (
            f"Target Post Title/Topic: {post_title}\n"
            f"Author/Source: {post_author or 'Industry Leader'}\n"
            f"Sector: {sector}\n"
            f"Post Content:\n{post_content}\n\n"
            "Draft the executive CTO comment now (no introduction, just the comment text):"
        )

        candidate_models = [
            self.text_model,
            "gemini-3.5-flash",
            "gemini-3.6-flash",
            "gemini-3.5-flash-lite",
            "gemini-3-flash-preview",
        ]
        candidate_models = list(dict.fromkeys(candidate_models))

        for model_name in candidate_models:
            try:
                resp = self.client.models.generate_content(
                    model=model_name,
                    contents=user_prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=system_instruction,
                        temperature=0.5,
                        max_output_tokens=2048,
                    ),
                )
                raw_text = resp.text.strip()
                if raw_text:
                    return clean_anti_ai_comment(raw_text)
            except Exception as e:
                logger.warning("Comment generation failed on %s: %s", model_name, e)
                continue

        # Pragmatic fallback if AI call fails
        return (
            "التحدي الحقيقي في مثل هذه التحولات لا يكمن في واجهات الاستخدام، بل في مرونة البنية التحتية "
            "وقدرة أنظمة الدفع وواجهات Open Banking على معالجة المعاملات اللحظية بأعلى معايير الـ SLA ودون أي اختناق."
        )


def discover_trending_sector_post() -> Dict[str, any]:
    """
    Finds a trending, highly relevant FinTech/PropTech/AI post or news item from the regional feeds.
    Returns metadata including title, link, sector, and content snippet.
    """
    unread = fetch_unread_articles()
    if unread:
        top_art = unread[0]
        # Clean summary
        summary = (top_art.summary or top_art.title).replace("\n", " ").strip()
        if len(summary) > 280:
            summary = summary[:277] + "..."
        return {
            "title": top_art.title,
            "source": top_art.source or "Saudi Tech Ecosystem",
            "url": top_art.link,
            "summary": summary,
            "sector": "FinTech & PropTech Saudi/GCC",
            "post_text": f"{top_art.title}\n\n{summary}",
            "is_feed_article": True,
        }

    # Curated regional breaking discussions as rich fallback
    return {
        "title": "تسارع اعتماد Open Banking والمعالجة اللحظية للمدفوعات في السوق السعودي",
        "source": "Fintech Saudi / SAMA Updates",
        "url": "https://www.linkedin.com/feed/",
        "summary": "تحديثات موسعة من البنك المركزي السعودي SAMA لتمكين شركات الفنتك من الربط المباشر مع واجهات المصارف المفتوحة وتسريع معالجة الحوالات الفورية.",
        "sector": "FinTech & Open Banking",
        "post_text": "البنك المركزي السعودي يعلن توسيع نطاق تراخيص المصرفية المفتوحة وربط شركات التقنية المالية ببنية الدفع اللحظي عبر معايير ISO 20022 الموحدة.",
        "is_feed_article": False,
    }


def draft_comment_for_target(
    target_url_or_urn: str = "",
    target_text: str = "",
    target_title: str = "",
) -> Dict[str, any]:
    """
    High-level orchestrator that:
    1. Resolves target post (either via user URL/text or auto-discovering sector trends).
    2. Drafts an anti-AI executive comment from Mohamed Elbaloty (CTO @ Sahalat).
    3. Normalizes target URN for LinkedIn API publishing.
    """
    resolved_url = target_url_or_urn.strip()
    resolved_text = target_text.strip()
    resolved_title = target_title.strip()
    source_name = ""

    # If no URL or text provided, discover a trending sector topic
    if not resolved_url and not resolved_text:
        trending = discover_trending_sector_post()
        resolved_title = trending["title"]
        resolved_url = trending["url"]
        resolved_text = trending["post_text"]
        source_name = trending["source"]
    elif resolved_url and not resolved_text:
        # User pasted a LinkedIn post URL: extract URN and guess title/slug
        urn = extract_urn_from_linkedin_url(resolved_url)
        slug_match = re.search(r"linkedin\.com/posts/([^/?]+)", resolved_url)
        if slug_match:
            slug = slug_match.group(1).replace("-", " ")
            resolved_title = f"منشور تقني: {slug[:60]}"
            resolved_text = f"نقاش قطاعي حول: {slug}"
        else:
            resolved_title = f"منشور على LinkedIn ({urn or 'تفاعل مجتمعي'})"
            resolved_text = "نقاش تنفيذي متخصص في قطاع التقنية المالية والتحول الرقمي والبنية التحتية السحابية."
        source_name = "LinkedIn Post"

    # Extract clean target URN if this is a LinkedIn post
    target_urn = extract_urn_from_linkedin_url(resolved_url)

    generator = CommentGenerator()
    comment = generator.generate_comment(
        post_content=resolved_text or resolved_title,
        post_title=resolved_title,
        post_author=source_name,
    )

    return {
        "success": True,
        "post_title": resolved_title,
        "post_url": resolved_url,
        "post_urn": target_urn,
        "post_content_snippet": resolved_text[:240] + ("..." if len(resolved_text) > 240 else ""),
        "comment_text": comment,
        "author_persona": "Mohamed Elbaloty, CTO @ Sahalat",
    }


def execute_linkedin_comment(
    target_urn_or_url: str,
    comment_text: str,
    post_title: str = "",
) -> Dict[str, any]:
    """
    Executes a live comment publish on LinkedIn and records the action in history.
    """
    target_urn = extract_urn_from_linkedin_url(target_urn_or_url)
    if not target_urn or not target_urn.startswith("urn:li:"):
        return {
            "success": False,
            "error": (
                f"رابط المنشور غير صالح أو لا يحتوي على معرف URN رسمي للينكد إن: '{target_urn_or_url}'. "
                "يرجى التأكد من وضع رابط منشور كامل مثل: https://www.linkedin.com/posts/..."
            ),
        }

    res = publish_comment_to_linkedin(target_urn_or_url=target_urn, comment_text=comment_text)

    # Record in history
    settings = load_comment_settings()
    today_str = datetime.now().strftime("%Y-%m-%d")
    if settings.get("last_comment_date") != today_str:
        settings["comments_today"] = 0
        settings["last_comment_date"] = today_str

    if res.get("success"):
        settings["comments_today"] = settings.get("comments_today", 0) + 1
        settings["last_comment_time"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    history_item = {
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "target_urn": target_urn,
        "post_title": post_title or target_urn,
        "comment_text": comment_text,
        "success": res.get("success", False),
        "public_url": res.get("public_url", f"https://www.linkedin.com/feed/update/{target_urn}"),
        "error": res.get("error"),
    }
    history = settings.get("history", [])
    history.insert(0, history_item)
    settings["history"] = history[:30]  # Keep last 30 comments
    save_comment_settings(settings)

    return res
